services:
  app1:
    build: .
    container_name: app1
    hostname: app1

  app2:
    build: .
    container_name: app2
    hostname: app2

  nginx:
    image: nginx:latest
    container_name: nginx_load_balancer
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2